print("Welcome to the Family Tax Form 1")

taxes = []

taxes.append(eval(input("Enter wages, salaries, and tips earned by the husband:")))
taxes.append(eval(input("Enter wages, salaries, and tips earned by the wife:")))
taxes.append(eval(input("Bonus earned by the family combined:")))
taxes.append(taxes[0] + taxes[1] + taxes[2])
print("This is your yearly gross income:")
print(taxes[3])
taxes.append(5000)
taxes.append(taxes[3] - taxes[4])
print("This is your taxable income:")
print(taxes[5])
taxes.append(eval(input("Federal income taxs withheld for husband:")))
taxes.append(eval(input("Federal income taxs withheld for wife:")))
taxes.append(taxes[6] + taxes[7])
print("This is your total payments and credits:")
print(taxes[8])
taxes.append(taxes[5] * .28)
print("Total Federal Tax:")
print(taxes[9])
taxes.append(eval(input("Property tax to be owed:")))
taxes.append(taxes[9] + taxes[10])
print("This is your total tax:")
print(taxes[11])
taxes.append(taxes[11] - taxes[8])
print("If result is positive, it is the amount you have to pay. If result is negative, it is the amount you have overpaid: ")
print(taxes[12])
